spring:
  application:
    name: 01-chat-openai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.2
          temperature: 1
      base-url: https://api.openai.com
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
